// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function normalizeDatabaseUrl(url?: string) {
  if (!url) {
    return url;
  }

  try {
    const parsedUrl = new URL(url);

    if (parsedUrl.protocol === "mysql:" || parsedUrl.protocol === "mariadb:") {
      if (parsedUrl.hostname === "localhost") {
        parsedUrl.hostname = "127.0.0.1";
      }

      const isLocalDatabase =
        parsedUrl.hostname === "127.0.0.1" ||
        parsedUrl.hostname === "localhost";

      if (
        isLocalDatabase &&
        !parsedUrl.searchParams.has("allowPublicKeyRetrieval") &&
        !parsedUrl.searchParams.has("rsaPublicKey") &&
        !parsedUrl.searchParams.has("cachingRsaPublicKey")
      ) {
        parsedUrl.searchParams.set("allowPublicKeyRetrieval", "true");
      }
    }

    return parsedUrl.toString();
  } catch {
    return url;
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: normalizeDatabaseUrl(process.env["DATABASE_URL"]),
  },
});
