const AUTH_ERROR_CODES = {
  PASSWORD_HASH_FAILED: "PASSWORD_HASH_FAILED",
  PASSWORD_COMPARE_FAILED: "PASSWORD_COMPARE_FAILED",
  NO_USER_FOUND: "NO_USER_FOUND",
  USER_CREATE_FAILED: "USER_CREATE_FAILED",
  USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
} as const;

export type AuthErrorCode =
  (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
